In [198]:

import sys
sys.path.append("././quaos")
from math import gcd
from collections import defaultdict
from itertools import product

import numpy as np
from hamiltonian import random_pauli_hamiltonian, cancel_pauli, symplectic_pauli_reduction, pauli_reduce
from symplectic import (
    PauliSum, PauliString, Pauli,
    #  Xnd, Ynd, Znd, Id, symplectic_to_string,
    string_to_symplectic,
)

In [ ]:

class Gate:
    """
    Mapping can be written as set of rules,
    
    e.g. for CNOT
                x1z0*x0z0 -> x1z0*x1z0
                x0z0*x1z0 -> x0z0*x1z0  # doesn't need specifying
                x0z1*x0z0 -> x0z1*x0z0  # doesn't need specifying
                x0z0*x0z1 -> x0z-1*x0z1 # 

    inputs are:

    mapping = ['x1z0*x0z0 -> x1z0*x1z0', 'x0z0*x0z1 -> -x0z1*x0z1']  # (control*target -> control*target)

    """
    def __init__(self, name: str, qudit_indices: list[int], mapping: list[str], dimension: list[int]):
        self.dimension = dimension
        self.name = name
        self.qudit_indices = qudit_indices
        self.mapping = mapping
        self.n_qudits = len(qudit_indices)
        self.symplectic = self._interpret_mapping(mapping)
        
    
    def _interpret_mapping(self, map_string: list[str]) -> tuple[np.ndarray, np.ndarray, list[int]]:
        map_from, map_to = zip(*[map_string[i].split('->') for i in range(len(map_string))])

        n_maps = len(map_from)

        symplectic_looked_for = []
        for i in range(n_maps):
            s, _ = string_to_symplectic(map_from[i])
            symplectic_looked_for.append(s)

        symplectic_mapped_to = []
        acquired_phase = []
        for i in range(len(map_from)):
            s, p = string_to_symplectic(map_to[i])
            symplectic_mapped_to.append(s)
            acquired_phase.append(p)
        
        # For an n qubit operation there should be a set of 2n mappings.
        # If the rest are unspecified, they should be identity mappings (those with equal looked_for and mapped_to)
        # If the user specifies less than 2n mappings, then the remaining ones will be identity mappings
        # These remaining identity mappings must all be linearly independent of the specified ones
        # note that this will fail if the input mappings are not of the form X*I*...*I, Z*I*...*I, (having only a single
        # X or Z in the string - checked for below) - generalisable if needed
        # This will only be needed to obtain the symplectic matrix for the gate operation, not for current method...
        if len(symplectic_looked_for) < 2 * self.n_qudits:
            for s in symplectic_looked_for:
                if np.sum(s) != 1:
                    raise Exception('Unable to automate completion of mappings. Specify 2*n_qudits linearly '
                                    'independent mappings to fully define the gate operation.')
            for i in range(2 * self.n_qudits):
                mapping = np.zeros(2 * self.n_qudits, dtype=int)
                mapping[i] = 1
                if not any(np.array_equal(mapping, arr) for arr in symplectic_looked_for):
                    print(mapping)
                    symplectic_looked_for.append(mapping)
                    symplectic_mapped_to.append(mapping)

        ## remove once debugged
        # assert len(symplectic_looked_for) == self.dimension * (self.n_qudits), (len(symplectic_looked_for),
        #                                                                              self.dimension * (self.n_qudits))
        # assert len(symplectic_mapped_to) == self.dimension * (self.n_qudits)
        ##

        symplectic_looked_for = np.array(symplectic_looked_for)
        symplectic_mapped_to = np.array(symplectic_mapped_to)

        # reorder such that the symplectic looked for is always the identity
        # (this would need to be altered to an arbitrary complete set generalise)
        perm = np.argmax(symplectic_looked_for, axis=1)
        inverse_perm = np.argsort(perm)
        symplectic_looked_for = symplectic_looked_for[inverse_perm]
        symplectic_mapped_to = symplectic_mapped_to[inverse_perm]

        symplectic = self.build_symplectic_from_mappings(symplectic_looked_for, symplectic_mapped_to)

        return symplectic
    
    def mod_inv(self, a):
        """Modular inverse of a mod d, where d = self.dimension."""
        a = a % self.dimension
        if a == 0:
            raise ValueError("0 has no inverse modulo d")
        return pow(int(a), -1, self.dimension)

    def mod_mat_inv(self, A):
        """Modular inverse of matrix A over Z_d using Gauss-Jordan elimination."""
        A = np.array(A, dtype=int) % self.dimension
        n = A.shape[0]
        I = np.eye(n, dtype=int)
        AI = np.hstack([A, I])  # Augmented matrix [A | I]

        for i in range(n):
            # Find pivot
            pivot = AI[i, i]
            if pivot == 0:
                # Try to swap with a lower row
                for j in range(i + 1, n):
                    if AI[j, i] != 0:
                        AI[[i, j]] = AI[[j, i]]
                        pivot = AI[i, i]
                        break
                else:
                    raise ValueError(f"Matrix {A} not invertible")

            # Normalize pivot row
            inv_pivot = self.mod_inv(pivot)
            AI[i] = (AI[i] * inv_pivot) % self.dimension

            # Eliminate other rows
            for j in range(n):
                if j != i:
                    factor = AI[j, i]
                    AI[j] = (AI[j] - factor * AI[i]) % self.dimension

        A_inv = AI[:, n:]  # Extract right half
        return A_inv

    def build_symplectic_from_mappings(self, looked_for, mapped_to):
        """Build symplectic matrix from Pauli generator mappings."""
        looked_for = np.array(looked_for, dtype=int) % self.dimension
        mapped_to = np.array(mapped_to, dtype=int) % self.dimension

        if looked_for.shape != mapped_to.shape:
            raise ValueError("Shape mismatch between looked_for and mapped_to.")
        # if looked_for.shape[0] != looked_for.shape[1]:
        #     raise ValueError("Expect square matrix of 2n symplectic vectors.", looked_for)

        inv_looked_for = self.mod_mat_inv(looked_for)
        S = (mapped_to @ inv_looked_for) % self.dimension
        return S


class SUM(Gate):
    def __init__(self, control, target, dimension):
        SGate_operations = self.sum_gate_operations(dimension)
        super().__init__("SUM", [control, target], SGate_operations, dimension=dimension)
   
    @staticmethod
    def sum_gate_operations(dimension: int) -> list[str]:
        operations = []
        for r1 in range(dimension):
            for s1 in range(dimension):
                for r2 in range(dimension):
                    for s2 in range(dimension):
                        new_r1 = r1
                        new_s1 = (s1 - s2) % dimension
                        new_r2 = (r2 + r1) % dimension
                        new_s2 = s2
                        phase = (r1 * s2) % dimension
                        if r1 != new_r1 or s1 != new_s1 or r2 != new_r2 or s2 != new_s2 or phase != 0:
                            operations.append(f"x{r1}z{s1} x{r2}z{s2} -> x{new_r1}z{new_s1} x{new_r2}z{new_s2}p{phase}")
        print( np.array(operations).T)
        print(len(operations))
        return operations

class SUMcs(Gate):
    def __init__(self, control, target, dimension):
        SGate_operations = self.sum_gate_operations(dimension)
        super().__init__("SUM", [control, target], SGate_operations, dimension=dimension)
   
    @staticmethod
    def sum_gate_operations(dimension: int) -> list[str]:
        operations = []
        for r1 in range(dimension):
            for s1 in range(dimension):
                for r2 in range(dimension):
                    for s2 in range(dimension):
                        new_r1 = r1
                        new_s1 = (s1 - s2) % dimension
                        new_r2 = (r2 + r1) % dimension
                        new_s2 = s2
                        phase = (r1 * s2) % dimension
                        if r1 + r2 + s1 + s2 == 1:
                            operations.append(f"x{r1}z{s1} x{r2}z{s2} -> x{new_r1}z{new_s1} x{new_r2}z{new_s2}p{phase}")
        print( np.array(operations).T)
        print(len(operations))
        return operations
    
    @staticmethod
    def sum_gate_images(dimension: int) -> list[str]:
        images = [np.array([1, 1, 0, 0]),  # image of X0:  X0 -> X0 X1
                  np.array([0, 1, 0, 0]),  # image of X1:  X1 -> X1
                  np.array([0, 0, 1, 0]),  # image of Z0:  Z0 -> Z0
                  np.array([0, 0, -1, 1])  # image of Z1:  Z1 -> Z0^-1 Z1
                  ]
        return images

In [65]:
sum_cs = SUMcs(1, 0, 3)
# sum_gate = SUM(0, 1, 2)
sum_cs.symplectic 
xi_symplectic = np.array([1, 0, 0, 0])
ix_symplectic = np.array([0, 1, 0, 0])
zi_symplectic = np.array([0, 0, 1, 0])
iz_symplectic = np.array([0, 0, 0, 1])
test_symplectic = np.array([1, 2, 2, 1])

print(sum_cs.symplectic)

print((sum_cs.symplectic.T @ xi_symplectic @ sum_cs.symplectic)% 3) 
print((sum_cs.symplectic.T @ ix_symplectic @ sum_cs.symplectic)% 3) 
print((sum_cs.symplectic.T @ zi_symplectic @ sum_cs.symplectic)% 3) 
print((sum_cs.symplectic.T @ iz_symplectic @ sum_cs.symplectic)% 3) 
print((sum_cs.symplectic.T @ test_symplectic @ sum_cs.symplectic)% 3) 



['x0z0 x0z1 -> x0z2 x0z1p0' 'x0z0 x1z0 -> x0z0 x1z0p0'
 'x0z1 x0z0 -> x0z1 x0z0p0' 'x1z0 x0z0 -> x1z0 x1z0p0']
4
[[1 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 2 1]]
[1 2 0 0]
[0 1 0 0]
[0 0 1 0]
[0 0 1 1]
[1 1 0 1]


In [ ]:
def str_to_int(string):
    output = []

    for s in string:
        if s == 'I':
            output.append(0)
        elif s == 'X':
            output.append(1)
        elif s == 'Y':
            output.append(2)
        elif s == 'Z':
            output.append(3)
    return output

def int_to_pauli(integer):
    if integer == 0:
        return [0, 0]
    elif integer == 1:
        return [1, 0]
    elif integer == 2:
        return [1, 1]
    elif integer == 3:
        return [0, 1]

def matrix_to_pauli_sum(matrix, weights, phases, dimensions):

    n_paulis = matrix.shape[0]
    n_qudits = matrix.shape[1]

    pauli_strings = []
    for i in range(n_paulis):
        x_exp = np.zeros(n_qudits, dtype=int)
        z_exp = np.zeros(n_qudits, dtype=int)
        for j in range(n_qudits):
            x_exp[j] = int_to_pauli(matrix[i, j])[0]
            z_exp[j] = int_to_pauli(matrix[i, j])[1]
        ps = PauliString(x_exp, z_exp, dimensions)
        pauli_strings.append(ps)

    return PauliSum(pauli_strings, weights, phases, dimensions, standardise=False)
    


def find_allowed_target(pauli_sum, target_pauli_list, ):
    pauli_list = [target_pauli_list[i][0] for i in range(len(target_pauli_list))]
    pauli_list = str_to_int(pauli_list)
    string_indices = [target_pauli_list[i][1] for i in range(len(target_pauli_list))]
    qudit_indices = [target_pauli_list[i][2] for i in range(len(target_pauli_list))]

    dims = pauli_sum.dimensions 
    combined_indices = list(zip(string_indices, qudit_indices))
    index_dict = defaultdict(list)

    for idx, tup in enumerate(combined_indices):
        index_dict[tup].append(idx)

    underdetermined_pauli_indices = [combined_indices[idxs[0]] for idxs in index_dict.values() if len(idxs) > 1]
    underdetermined_pauli_options = []
    for indices in underdetermined_pauli_indices:
        options = []
        for i in range(len(target_pauli_list)):
            if target_pauli_list[i][1] == indices[0] and target_pauli_list[i][2] == indices[1]:
                if target_pauli_list[i][0] not in options:
                    options.append(target_pauli_list[i][0])
        underdetermined_pauli_options.append(options)
    underdetermined_pauli_options = [str_to_int(l) for l in underdetermined_pauli_options]

    determined_pauli_indices = [combined_indices[idxs[0]] for idxs in index_dict.values() if len(idxs) == 1]

    options_matrix = np.empty([pauli_sum.n_paulis(), pauli_sum.n_qudits()], dtype=object)
    for i in range(pauli_sum.n_paulis()):
        for j in range(pauli_sum.n_qudits()):
            if (i, j) in underdetermined_pauli_indices:
                options_matrix[i, j] = underdetermined_pauli_options[underdetermined_pauli_indices.index((i, j))]
            elif (i, j) in determined_pauli_indices:
                options_matrix[i, j] = [pauli_list[determined_pauli_indices.index((i, j))]]
            else:
                options_matrix[i, j] = [0, 1, 2, 3]
    
    flag_matrix = np.zeros([pauli_sum.n_paulis(), pauli_sum.n_qudits()], dtype=int)  # flag matrix to track which indices are determined 
    # 0 for not determined, 1 for underdetermined, -1 for determined
    for idx, tup in enumerate(combined_indices):
        if tup in underdetermined_pauli_indices:
            flag_matrix[tup[0], tup[1]] = -1  # -1 for underdetermined
        else:
            flag_matrix[tup[0], tup[1]] = 1  # 1 for determined

    spm = pauli_sum.symplectic_product_matrix()
    
    possible_targets = []
    for combo in product(*options_matrix.flatten()):
        combo = np.reshape(combo, (pauli_sum.n_paulis(), pauli_sum.n_qudits()))
        pauli_sum_candidate = matrix_to_pauli_sum(combo, pauli_sum.weights, pauli_sum.phases, dims)
        candidate_spm = pauli_sum_candidate.symplectic_product_matrix()

        if np.all(spm == candidate_spm):
            possible_targets.append(pauli_sum_candidate)
    return possible_targets



In [ ]:
init_sum = ['x1z0 x0z0', 'x1z0 x0z1', 'x0z1 x1z1']
init_sum = PauliSum(init_sum, dimensions=[2, 2])
print(init_sum)
target_paulis = [('X', 0, 0), ('I', 0, 1), ('Z', 1, 0), ('I', 1, 0), ('Z', 2, 0), ('I', 2, 0)]  #

targets = find_allowed_target(init_sum, target_paulis)

print(len(targets))
for t in targets:
    print(t)

SORTING
(1+0j)|x1z0 x0z0 | 0 
(1+0j)|x1z0 x0z1 | 0 
(1+0j)|x0z1 x1z1 | 0 

[[list([1]) list([0])]
 [list([3, 0]) list([0, 1, 2, 3])]
 [list([3, 0]) list([0, 1, 2, 3])]]
[<symplectic.PauliSum object at 0x7f667f6d6f00>, <symplectic.PauliSum object at 0x7f667f48dbe0>, <symplectic.PauliSum object at 0x7f667f48fd40>, <symplectic.PauliSum object at 0x7f667f48dcd0>, <symplectic.PauliSum object at 0x7f667f48d610>, <symplectic.PauliSum object at 0x7f667f48e9c0>, <symplectic.PauliSum object at 0x7f667f48f5f0>, <symplectic.PauliSum object at 0x7f667f3108f0>, <symplectic.PauliSum object at 0x7f667f310ec0>, <symplectic.PauliSum object at 0x7f667f48df70>]
10
(1+0j)|x1z0 x0z0 | 0 
(1+0j)|x0z0 x0z0 | 0 
(1+0j)|x0z1 x0z0 | 0 

(1+0j)|x1z0 x0z0 | 0 
(1+0j)|x0z0 x0z0 | 0 
(1+0j)|x0z1 x1z0 | 0 

(1+0j)|x1z0 x0z0 | 0 
(1+0j)|x0z0 x0z0 | 0 
(1+0j)|x0z1 x1z1 | 0 

(1+0j)|x1z0 x0z0 | 0 
(1+0j)|x0z0 x0z0 | 0 
(1+0j)|x0z1 x0z1 | 0 

(1+0j)|x1z0 x0z0 | 0 
(1+0j)|x0z0 x1z0 | 0 
(1+0j)|x0z1 x0z0 | 0 

(1+0j)|x1z0 