In [1]:
import numpy as np
from quaos.core.paulis import PauliSum, PauliString
from quaos.core.circuits.target import find_map_to_target_pauli_sum
from quaos.core.circuits.gates import Gate
from quaos.utils import get_linear_dependencies
from quaos.graph_utils import find_one_permutation, permutation_to_swaps, mapping_key
from quaos.models import ToricCode

First we make a random Pauli Sum, and obtain a list of the linearly independent rows

In [3]:
toric = True

if toric:
    d = 2

    Nx = 2
    Ny = 2
    periodic = True
    c_x = 1.
    c_z = 1.
    c_g = 1.

    TC = ToricCode(Nx, Ny, c_x, c_z, c_g, periodic)
    H = TC.hamiltonian()

else:
    # parameters
    n_paulis = 9
    n_qudits = 4
    d = 2
    n_weights = 1 # number of different weights

    dimensions = [d] * n_qudits
    # make a random pauli sum
    H = PauliSum.from_random(n_paulis, n_qudits, dimensions, rand_weights=False)

    # this bit makes sections of H have different weights
    weights = np.empty(n_paulis, dtype=int)
    section_size = n_paulis // n_weights
    for i in range(n_weights):
        start = i * section_size
        end = (i + 1) * section_size if i < n_weights - 1 else n_paulis
        weights[start:end] = i + 1

    H.weights = weights
    # print(H.symplectic())

# obtain linearly independent rows - note this fails sometimes as there is a solver in it that
# is not that robust. The Clifford approach is more robust as it creates a simple basis where the
# dependencies can be easily read.
independent_paulis, dependencies = get_linear_dependencies(H.symplectic(), d)

print(independent_paulis)
print(dependencies)

[0, 1, 2, 3, 4, 5, 8, 9, 12, 13, 14]
{6: [(0, 1), (1, 1), (4, 1), (5, 1)], 7: [(2, 1), (3, 1), (4, 1), (5, 1)], 10: [(0, 1), (1, 1), (8, 1), (9, 1)], 11: [(2, 1), (3, 1), (8, 1), (9, 1)], 15: [(12, 1), (13, 1), (14, 1)]}


We now solve for possible permutations which leave the dependencies unchanged

To do so we make a dictionary with labels of the coefficients

***Note this will only work for qubits for now, as for qudits we also need to account for the fact that a dependency can be made of $P_i + kP_j$ for some integer $k < d$***

In [4]:
cs = H.weights

graph_dict = {}

for i in independent_paulis:
    key = cs[i]
    if key in graph_dict:
        graph_dict[key].append([i])
    else:
        graph_dict[key] = [[i]]

for i in dependencies.keys():
    key = cs[i]
    dependency = dependencies[i]
    dependence_indices = [x[0] for x in dependency]
    dependence_multiplicities = [x[1] for x in dependency]  # this will be needed for qudits! always 1 for now
    if key in graph_dict:
        graph_dict[key].append(dependence_indices)
    else:
        graph_dict[key] = [dependence_indices]

print(graph_dict)

{np.complex128(1+0j): [[0], [1], [2], [3], [4], [5], [8], [9], [12], [13], [14], [0, 1, 4, 5], [2, 3, 4, 5], [0, 1, 8, 9], [2, 3, 8, 9], [12, 13, 14]]}


We then test to see if any indexes have an automorphism that can be found via a simple swap

***There is an additional condition - the pairs when swapped must leave the symplectic product matrix invariant...***
As there is always going to be a reasonably small number of pairs, we can probably check the combinatorial number of
options for this...

In [12]:

permutation = ()
permutations_attempted = set()
found = False
i = 0
while not found:
    i += 1
    print(f"Attempting permutation {i}")
    permutation = find_one_permutation(graph_dict[1], np.ones(len(graph_dict[1]), dtype=int), permutations_attempted, 
                                       max_cycle_size=10)
    print(permutation)
    if permutation is None:
        raise ValueError("No valid permutation found")
    pairs = permutation_to_swaps(permutation)
    H_target = H.copy()
    for p in pairs:
        H_target.swap_paulis(p[0], p[1])
        if np.array_equal(H_target.symplectic_product_matrix(), H.symplectic_product_matrix()):
            found = True
            print("Found automorphism")
            break
        else:
            print("Not an automorphism, trying next permutation")
            permutations_attempted.add(mapping_key(permutation, domain=sorted({x for lst in graph_dict[1] for x in lst})))

print(pairs)

Attempting permutation 1
{0: 1, 1: 0, 2: 2, 3: 3, 4: 4, 5: 5, 8: 8, 9: 9, 12: 12, 13: 13, 14: 14}
Not an automorphism, trying next permutation
Attempting permutation 2
{0: 0, 1: 1, 2: 3, 3: 2, 4: 4, 5: 5, 8: 8, 9: 9, 12: 12, 13: 13, 14: 14}
Not an automorphism, trying next permutation
Attempting permutation 3
{0: 0, 1: 1, 2: 2, 3: 3, 4: 5, 5: 4, 8: 8, 9: 9, 12: 12, 13: 13, 14: 14}
Not an automorphism, trying next permutation
Attempting permutation 4
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 8: 9, 9: 8, 12: 12, 13: 13, 14: 14}
Not an automorphism, trying next permutation
Attempting permutation 5
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 8: 8, 9: 9, 12: 13, 13: 12, 14: 14}
Not an automorphism, trying next permutation
Attempting permutation 6
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 8: 8, 9: 9, 12: 14, 13: 13, 14: 12}
Not an automorphism, trying next permutation
Attempting permutation 7
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 8: 8, 9: 9, 12: 12, 13: 14, 14: 13}
Not an automorphism, trying next permutation

Now we choose a target - for this example, performing all of these swaps

We then find the symplectic which maps the original H to H_target

In [24]:
# found = False
# # make target
# H_target = H.copy()
# for p in pairs:  # This is inefficient - could be done better by checking only the commutation of Paulis to be swapped
#     H_target.swap_paulis(p[0], p[1])
#     if np.array_equal(H_target.symplectic_product_matrix(), H.symplectic_product_matrix()):
#         found = True
#         print("Found automorphism")
#         break

# if not found:
#     print("No automorphism found - there are only non-Pauli symmetries if the rank of H is < 2n")
#     H_target = H.copy()


# find F
# It may be here that we need to use only the paulis that are linearly independent
H_indep = H[independent_paulis]
H_t_indep = H_target[independent_paulis]

print(H_indep.symplectic_product_matrix() == H_t_indep.symplectic_product_matrix())

# print(H_indep)
# print(H_t_indep)


F, _, _, _ = find_map_to_target_pauli_sum(H_indep, H_t_indep)

# print(F)
# check F

print(H_t_indep.symplectic() - (H_indep.symplectic() @ F) % d)
# print(H.symplectic() @ F % d)
# print(np.array_equal(H_target.symplectic(), H.symplectic() @ F % d))
# print(F)


[[ True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True]]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 -1  0 -1  