In [1]:
import sys
import os
new_path = r'c:\Users\Rick\Desktop\VSCode\quaos\src'
# Change working directory
os.chdir(new_path)

print(os.getcwd())
#sys.path.append(os.path.abspath(".."))
import numpy as np
import glob

import pickle
#import occam
import random
import copy

c:\Users\Rick\Desktop\VSCode\quaos\src


In [2]:
import numpy as np
import quaos.random as quaos_random
from quaos.core.circuits import Gate, Hadamard as H, PHASE as S, Circuit
from quaos.core.paulis import PauliSum


In [3]:
def invert_gate(G):
    g_name = G.name
    g_dim = G.dimension
    g_qudit_indices = G.qudit_indices
    g_phase_vector = G.phase_vector
    g_symplectic = np.array(G.images)
    Omega = quaos_random._symplectic_form(int(g_symplectic.shape[0]/2))
    g_inv_symplectic = (Omega.T @ g_symplectic.T @ Omega)%2
    g_inv_symplectic = g_inv_symplectic.tolist()
    g_inv_symplectic = [np.array(v) for v in g_inv_symplectic]
    G_inv = Gate(
        name=g_name + "_inv",
        dimension=g_dim,
        qudit_indices=g_qudit_indices,
        phase_vector=g_phase_vector,
        images=g_inv_symplectic
    )
    return(G_inv)

In [4]:
g = quaos_random.clifford([2,2,2,2,2])
g.symplectic

array([[1, 0, 1, 1, 0, 0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 0, 1, 1, 0, 1, 0, 1, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 1, 1, 1],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 1, 1, 1, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 1, 0, 1, 0, 1, 1]], dtype=int32)

In [5]:
P = quaos_random.pauli_hamiltonian(5,15,0,3)
print(P)

(1+0j)|x0z1 x0z0 x1z0 x0z1 x0z1 | 0 
(1+0j)|x1z1 x1z1 x0z1 x0z1 x1z1 | 2 
(1+0j)|x1z0 x1z0 x1z0 x0z0 x0z1 | 0 
(1+0j)|x1z1 x1z0 x1z1 x0z0 x0z1 | 0 
(1+0j)|x0z0 x0z0 x1z0 x1z1 x0z0 | 0 
(1+0j)|x0z1 x0z0 x0z0 x1z0 x1z0 | 3 
(1+0j)|x1z1 x1z0 x0z1 x0z0 x0z0 | 3 
(1+0j)|x0z0 x0z0 x1z1 x0z1 x1z0 | 1 
(1+0j)|x0z0 x0z1 x0z0 x1z0 x0z1 | 3 
(1+0j)|x1z1 x1z1 x0z1 x1z0 x0z1 | 2 
(1+0j)|x1z1 x1z0 x0z1 x0z0 x1z1 | 2 
(1+0j)|x1z0 x1z1 x0z0 x0z1 x1z1 | 2 
(1+0j)|x1z1 x1z1 x0z0 x0z0 x1z1 | 1 
(1+0j)|x0z1 x0z0 x0z0 x0z1 x1z1 | 0 
(1+0j)|x0z0 x0z0 x1z1 x0z1 x0z1 | 0 



In [6]:
def random_sym_Pauli(G, n_qudits=None, n_paulis=None):
    if n_qudits is None:
        n_qudits = G.dimension + 1
    if n_paulis is None:
        n_paulis = 2* n_qudits  
    P = quaos_random.pauli_hamiltonian(n_qudits,n_paulis,0,0)
    G_inv = invert_gate(G)
    P_prime = G_inv.act(P)
    P_sym = P + P_prime
    return(P_sym)
        

In [8]:
print(random_sym_Pauli(H(0,2), n_qudits=None, n_paulis=None))

(1+0j)|x1z1 x0z0 x1z1 | 0 
(1+0j)|x0z0 x0z1 x0z1 | 3 
(1+0j)|x0z1 x0z1 x1z0 | 3 
(1+0j)|x0z1 x1z0 x0z0 | 1 
(1+0j)|x1z1 x0z1 x1z1 | 0 
(1+0j)|x0z1 x1z0 x1z1 | 0 
(1+0j)|x1z1 x0z0 x1z1 | 2 
(1+0j)|x0z0 x0z1 x0z1 | 3 
(1+0j)|x1z0 x0z1 x1z0 | 3 
(1+0j)|x1z0 x1z0 x0z0 | 1 
(1+0j)|x1z1 x0z1 x1z1 | 2 
(1+0j)|x1z0 x1z0 x1z1 | 0 



In [ ]:
def invert_gate(G):
    g_name = G.name
    g_dim = G.dimension
    g_qudit_indices = G.qudit_indices
    g_phase_vector = G.phase_vector
    g_symplectic = np.array(G.images)
    Omega = quaos_random._symplectic_form(int(g_symplectic.shape[0]/2))
    g_inv_symplectic = (Omega.T @ g_symplectic.T @ Omega)%2
    g_inv_symplectic = g_inv_symplectic.tolist()
    g_inv_symplectic = [np.array(v) for v in g_inv_symplectic]
    G_inv = Gate(
        name=g_name + "_inv",
        dimension=g_dim,
        qudit_indices=g_qudit_indices,
        phase_vector=g_phase_vector,
        images=g_inv_symplectic
    )
    return(G_inv)

In [23]:
G = invert_gate(S(0,2))
np.array(G.images)

array([[1, 1],
       [0, 1]])

In [5]:
def symplectic_form(n):
    """Return the standard 2n x 2n symplectic form matrix."""
    I = np.identity(n, dtype=np.uint8)
    O = np.zeros((n, n), dtype=np.uint8)
    return np.block([
        [O, I],
        [I, O]
    ])

def symplectic_dot(u, v, J):
    """Symplectic inner product: u^T J v mod 2"""
    return int(np.dot(u, J @ v) % 2)

def random_isotropic_vector(J):
    """Generate a random vector v such that <v, v> = 0."""
    i = 0
    while True:
        print(i)
        i +=1
        v = np.random.randint(0, 2, size=(J.shape[0],), dtype=np.uint8)
        if symplectic_dot(v, v, J) == 0:
            return v

In [180]:
J = symplectic_form(4)

print(random_isotropic_vector(J).reshape(-1, 1))

0
[[1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]]


In [ ]:
def random_cliffords(tableau, n_gates):
    _, _, qubits = tableau.shape
    gates = np.random.choice(CLIFFORDS, int(n_gates))

    for i in range(n_gates):
        # generate a random array of 2-tuples with c_gate and optional t_gate
        q = np.random.choice(qubits, 2, replace=False)
        gates[i] = gates[i](q[0], q[1])

        # apply gate
        tableau = gates[i](tableau)

    return tableau, gates


def synthetic_symmetries(qubits, r, c):
    symm_row= 2*r+c

    tableau_s = np.zeros([2, symm_row, qubits], dtype='int')
    np.fill_diagonal(tableau_s[0, :r, :r], 1)
    np.fill_diagonal(tableau_s[1, r:2*r, :r], 1)
    np.fill_diagonal(tableau_s[1, 2*r:, r:r+c], 1)

    return tableau_s


def commute(tableau_a, tableau_b):
    """
    returns True if every term in tableau_a commutes
    with every term in tableau_b.
    """
    if (len(tableau_a.shape) < 3) or (len(tableau_b.shape) < 3):
        return True

    _, r, c = tableau_a.shape

    for i in range(r):
        xor_ab = np.logical_xor(tableau_a[:, i, :].reshape(2, 1, c), tableau_b) # false if both are same paulis
        and_ab = np.logical_and(tableau_a[:, i, :].reshape(2, 1, c), tableau_b) # false if 0s
        out = np.logical_and(and_ab, xor_ab)
        f = out.sum()
        if f != 0:
            return False

    return True

In [ ]:
qubits = 4 # number of qubits

factors = np.array(range(1, 5))
paulis_n = np.array([qubits, qubits**2]) #, qubits**4])
paulis = np.array(['I', 'X', 'Y', 'Z'])
samples = 1
N = np.random.choice(factors, 1) * np.random.choice(paulis_n, 1)

tableau_list=[]
cliff_tableau_list = []
ckt_list=[]
symm_list=[]
j = 0
print(factors, paulis_n, paulis,N)
print()
print('Schleife')
while (j < samples):
    N = np.random.choice(factors, 1) * np.random.choice(paulis_n, 1)
    print('N',N)
    coeff = N[0] #number of Paulis
    print('coeff',coeff)
    list_qubits = [int(i) for  i in np.arange(qubits)]
    print('list_qubits',list_qubits)

    # redundant qubits
    c = random.sample(list_qubits[1:-1], 1)[0] # conserved qubits
    print('c',c)
    left_qubits=[int(i) for i in np.arange(qubits-c)]# qubits without conserved qubits
    print('list_qubits',left_qubits)
    s = random.sample(left_qubits[1:], 1)[0]
    print('s',s)
    r = qubits - c - s  # remainder of qubits
    print('r',r)
    print()
    print('Zweite Schleife')
    while (coeff - (2 * s + c)) < 0:
        print(coeff - (2 * s + c))
        c = random.sample(list_qubits[1:-1], 1)[0] # conserved qubits
        print(c)
        left_qubits=[int(i) for i in np.arange(qubits-c)]# qubits without conserved qubits
        print(left_qubits)
        s = random.sample(left_qubits[1:], 1)[0]
        print(s)
        r = qubits - c - s  # remainder of qubits
        print(r)

    print('Exit Zweite Schleife')
    tableau = np.zeros([2, coeff, qubits], dtype='int')

    #Fill lower right block of shape np-(2s+c), c with random ones and zeros for both tabs
    tableau[0, 2*s+c:, r+c:]=np.random.randint(0, 2, [coeff-(2*s+c), s])
    tableau[1, 2*s+c:, r+c:]=np.random.randint(0, 2, [coeff-(2*s+c), s])

    #Fill lower 2nd-middle block of shape np-(2s+c), c with random ones and zeros for z-tableau
    tableau[1, 2*s+c:, r:r+c]=np.random.randint(0, 2, [coeff-(2*s+c), c])

    #Fill diagonal of the upper right block of shape s, s with ones and lower triangle with rand(0, 1) for z-tableau
    mask= np.tril(np.random.randint(0, 2, [s, s]), k=-1)
    tableau[1, :s, r+c:]=mask
    np.fill_diagonal(tableau[1, :s, r+c:], 1)
    j+=1
    print(tableau)
    '''
     #Fill diagonal of the upper middle block of shape s, s with ones and lower triangle with rand(0, 1) for x-tableau
    mask= np.tril(np.random.randint(0, 2, [s, s]), k=-1)
    tableau[0, s:2*s, r+c:]=mask
    np.fill_diagonal(tableau[0, s:2*s, r+c:], 1)

    #Fill diagonal of the lower midlle block of shape c, c with ones and lower triangle with rand(0, 1) for z-tableau
    mask= np.tril(np.random.randint(0, 2, [c, c]), k=-1)
    tableau[1,2*s:2*s+c, r:r+c]=mask
    np.fill_diagonal(tableau[1, 2*s:2*s+c, r:r+c], 1)

    if np.all(tableau[:, :, :r]==0):
        tableau_list.append((tableau, r, c, s))
        # remove duplicates
        flatten_tableau = np.swapaxes(tableau, 0, 1).reshape(coeff, qubits*2)
        _, unique_idx = np.unique(flatten_tableau, axis=0, return_index=True)
        tableau = tableau[:, np.sort(unique_idx), :]

        tab= copy.deepcopy(tableau)

        randomized_tableau, a_gates = random_cliffords(tab, coeff)

        cliff_tableau_list.append((randomized_tableau, r, c, s))
        ckt_list.append(a_gates)

        symm_list.append((synthetic_symmetries(qubits, r, c), r, c, s))

    else:
        assert False, "Tableau not initialized correctly"


    j+=1



symm_rand=[]
for ckt, symm in zip(ckt_list, symm_list):
    symm1= copy.deepcopy(symm[0])
    for gate in ckt:
        symm1= gate(symm1)

    symm_rand.append(symm1)

for symm, cliff_tab in zip(symm_rand, cliff_tableau_list):
    if commute(symm, cliff_tab[0]) != True:
        print('Error')


wd = os.getcwd()
dir_name= 'input_ham'+str(qubits)+'new_'+str(samples)
dir = os.path.join(wd, dir_name)

if not os.path.exists(dir):
    os.makedirs(dir)

j=0
for symm, cliff_tab in zip(symm_rand, cliff_tableau_list):
    out = { "r": cliff_tab[1],
            "c": cliff_tab[2],
            "s": cliff_tab[3],
            "hamiltonian": cliff_tab[0],
            "conserved": symm}

    if qubits<10:
        fn = f"0{qubits}ham_{j}.pkl"
    else:
        fn = f"{qubits}ham_{j}.pkl"
    fp = os.path.join(dir, fn)

    with open(fp, 'wb') as fp:
        pickle.dump(out, fp)

    j+=1

'''

[1 2 3 4] [ 4 16] ['I' 'X' 'Y' 'Z'] [32]

Schleife
N [16]
coeff 16
list_qubits [0, 1, 2, 3]
c 1
list_qubits [0, 1, 2]
s 1
r 2

Zweite Schleife
Exit Zweite Schleife
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 1]
  [0 0 0 1]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 1]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 1]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 1]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 1]
  [0 0 0 0]
  [0 0 0 1]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 1 1]
  [0 0 1 1]
  [0 0 0 1]
  [0 0 0 1]
  [0 0 1 1]
  [0 0 0 0]
  [0 0 1 1]]]
